### ISSUE TITLE
DynamicTrees not loading on aternos server 

### ISSUE THREAD

**Issue by BBCenjoyyer** [DynamicTreesTeam/DynamicTrees#722]
Description
Dynamic trees is not dynamizing my trees on a forge 1.16.5 36.2.34 aternos server
To Reproduce
Joining servers
Screenshots
none
Rendering Glitches
I dont use optifine
Additional context
none
only happens on servers
Crashes
none
Mods List
[1.16.5] SecurityCraft v1.9.3.1.jar
2.76 MB
alexsmobs-1.12.1.jar
17.30 MB
architectury-1.32.66.jar
538.96 kB
armorplus-1.16.5-16.8.1.jar
2.24 MB
AutoRegLib-1.6-49.jar
55.94 kB
Better Fishing Rods 1.3.0 - 1.16.5.jar
158.51 kB
betteranimalsplus-1.16.5-11.0.5-forge.jar
2.07 MB
BetterMineshafts-Forge-1.16.4-2.0.4.jar
282.53 kB
Bookshelf-Forge-1.16.5-10.4.32.jar
308.83 kB
Botania-1.16.5-420.jar
14.35 MB
Chisel-MC1.16.5-2.0.1-alpha.4.jar
6.97 MB
citadel-1.8.1-1.16.5.jar
471.13 kB
cloth-config-4.15.82-forge.jar
1.36 MB
CodeChickenLib-1.16.5-4.0.7.445-universal.jar
621.58 kB
Coins-1.16.5-6.0.3.jar
39.98 kB
CraftingTweaks_1.16.5-12.2.1.jar
108.58 kB
CreativeCore_v2.2.1_mc1.16.5.jar
616.41 kB
CTM-MC1.16.1-1.1.2.6.jar
181.71 kB
curios-forge-1.16.5-4.0.8.2.jar
271.34 kB
CustomNPCs-1.16.5.20220515.jar
11.88 MB
DungeonsArise-1.16.5-2.1.47-release.jar
4.46 MB
DynamicTrees-1.16.5-0.10.0-Beta34.jar
1.90 MB
DynamicTreesPlus-1.16.5-0.10.0-Beta12.jar
267.03 kB
elevatorid-1.16.5-1.7.13.jar
179.44 kB
FallingTree-1.16.5-2.11.5.jar
1.10 MB
geckolib-forge-1.16.5-3.0.90.jar
3.35 MB
jei-1.16.5-7.7.1.152.jar
809.25 kB
jev-1.16.3-2.0.1.jar
29.28 kB
journeymap-1.16.5-5.8.5p5.jar
6.38 MB
mcw-doors-1.0.7-mc1.16.5.jar
779.61 kB
obfuscate-0.6.3-1.16.5.jar
139.20 kB
OPF-1.16.x-v2.jar
227.58 kB
Patchouli-1.16.4-53.3.jar
579.45 kB
PlayerRevive_v2.0.0-pre04_mc1.16.5.jar
5.03 MB
Quark-r2.4-322.jar
8.39 MB
SewingKit-1.16.5-1.3.1.jar
174.63 kB
shutupexperimentalsettings-1.0.3.jar
4.04 kB
sophisticatedbackpacks-1.16.5-3.15.18.698.jar
1.42 MB
SpartanShields-1.16.5-2.1.2.jar
433.12 kB
thedragonlib-1.16.3-1.1.0.jar
37.43 kB
ToolBelt-1.16.5-1.16.2.jar
236.96 kB
vehicle-mod-0.45.2-1.16.3.jar
3.24 MB
voicechat-forge-1.16.5-2.3.9.jar
7.46 MB
YungsApi-1.16.4-Forge-13.jar
Versions
- Dynamic Trees:1.16.5-0.10.0-Beta34.jar
- DynamicTreesPlus-1.16.5-0.10.0-Beta12.jar
- Forge:1.16.5 36.2.34
- Java: 1.8.0_341/1.8.0_51
- OS:Windows 11

**Comment by Harleyoc1** [comment]
Please send a crash report.

**Comment by BBCenjoyyer** [comment]
I did not have any crashes
it simply doesnt work but I do have the dyanmictrees book

**Comment by Harleyoc1** [comment]
OK, what is the problem then? The title suggests it's not loading which I assumed meant it is crashing. Are you meaning it doesn't spawn any trees? If so please make sure you aren't using a custom world generator that is incompatible with DT.
